// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTblUser = "tbl_users"

// TblUser mapped from table <tbl_users>
type TblUser struct {
	UserID         int32     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	UserName       string    `gorm:"column:user_name;not null" json:"user_name"`
	Password       string    `gorm:"column:password;not null" json:"password"`
	Question       string    `gorm:"column:question;not null" json:"question"`
	Answer         string    `gorm:"column:answer;not null" json:"answer"`
	Sex            int32     `gorm:"column:sex;not null" json:"sex"`
	Birthday       time.Time `gorm:"column:birthday;not null;default:2000-01-01" json:"birthday"`
	UserMoney      float64   `gorm:"column:user_money;not null;default:0.00" json:"user_money"`
	FrozenMoney    float64   `gorm:"column:frozen_money;not null;default:0.00" json:"frozen_money"`
	PayPoints      int32     `gorm:"column:pay_points;not null" json:"pay_points"`
	RankPoints     int32     `gorm:"column:rank_points;not null" json:"rank_points"`
	AddressID      int32     `gorm:"column:address_id;not null" json:"address_id"`
	RegTime        int32     `gorm:"column:reg_time;not null" json:"reg_time"`
	LastLogin      int32     `gorm:"column:last_login;not null" json:"last_login"`
	LastTime       time.Time `gorm:"column:last_time;not null;default:2000-01-01 00:00:00" json:"last_time"`
	LastIP         string    `gorm:"column:last_ip;not null" json:"last_ip"`
	VisitCount     int32     `gorm:"column:visit_count;not null" json:"visit_count"`
	UserRank       int32     `gorm:"column:user_rank;not null" json:"user_rank"`
	IsSpecial      int32     `gorm:"column:is_special;not null" json:"is_special"`
	EcSalt         string    `gorm:"column:ec_salt" json:"ec_salt"`
	Salt           string    `gorm:"column:salt;not null;default:0" json:"salt"`
	ParentID       int32     `gorm:"column:parent_id;not null" json:"parent_id"`
	Flag           int32     `gorm:"column:flag;not null" json:"flag"`
	Alias_         string    `gorm:"column:alias;not null" json:"alias"`
	Msn            string    `gorm:"column:msn;not null" json:"msn"`
	Qq             string    `gorm:"column:qq;not null" json:"qq"`
	OfficePhone    string    `gorm:"column:office_phone;not null" json:"office_phone"`
	HomePhone      string    `gorm:"column:home_phone;not null" json:"home_phone"`
	MobilePhone    string    `gorm:"column:mobile_phone;not null" json:"mobile_phone"`
	IsValidated    int32     `gorm:"column:is_validated;not null" json:"is_validated"`
	CreditLine     float64   `gorm:"column:credit_line;not null" json:"credit_line"`
	PasswdQuestion string    `gorm:"column:passwd_question" json:"passwd_question"`
	PasswdAnswer   string    `gorm:"column:passwd_answer" json:"passwd_answer"`
}

// TableName TblUser's table name
func (*TblUser) TableName() string {
	return TableNameTblUser
}
